#!/bin/sh

# Install Packer.nvim
[ ! -e $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim/ ] &&\
	mkdir -p $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim/ &&\
	git clone --depth 1 https://github.com/wbthomason/packer.nvim\
	$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim/
