#!/bin/sh

# This is so stow does not link folders, only files
mkdir -p ~/.config/{kitty,i3,rofi,polybar}/
mkdir -p ~/.config/nvim/plugged/
mkdir -p ~/.config/qutebrowser/{bookmarks,qsettings}/

# Install Packer.nvim
[ ! -e $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim/ ] &&\
	mkdir -p $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim/ &&\
	git clone --depth 1 https://github.com/wbthomason/packer.nvim\
	$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim/

# Install Custom bash on bash
[ -z "`grep '.bash_aliases' ~/.bashrc`" ] &&\
	echo '[ -f ~/.bash_aliases ] && source ~/.bash_aliases' >> ~/.bashrc

# Add a file with dotfiles path on home (used on .bash_aliases)
echo $(dirname `realpath $0`) > ~/.dotfiles.path
