#!/bin/bash

get_status() {
	cat /sys/class/power_supply/BAT1/status
}

get_current() {
	cat /sys/class/power_supply/BAT1/charge_now
}

get_max() {
	cat /sys/class/power_supply/BAT1/charge_full
}

batt_percentage() {
	bc <<< $(get_current)*100/$(get_max)
}

print_stats() {
	echo NOTIFIED_5 ${NOTIFIED_5}
	echo NOTIFIED_10 ${NOTIFIED_10}
	echo NOTIFIED_20 ${NOTIFIED_20}
	echo NOTIFIED_30 ${NOTIFIED_30}
}

NOT_NOTIFIED_5=true
NOT_NOTIFIED_10=true
NOT_NOTIFIED_20=true
NOT_NOTIFIED_30=true

while true
do
	OPTION=$(get_status)
	case ${OPTION}
	in
		Discharging)
			if [ $(batt_percentage) -le 5 ] && ${NOT_NOTIFIED_5}
			then
				notify-send -u critical "Coloca o note p carregar ae o seu feladaputa"
				NOT_NOTIFIED_5=false
				NOT_NOTIFIED_10=false
				NOT_NOTIFIED_20=false
				NOT_NOTIFIED_30=false
			elif [ $(batt_percentage) -le 10 ] && ${NOT_NOTIFIED_10}
			then
				notify-send "Discharging: $(batt_percentage)% left"
				NOT_NOTIFIED_10=false
				NOT_NOTIFIED_20=false
				NOT_NOTIFIED_30=false
			elif [ $(batt_percentage) -le 20 ] && ${NOT_NOTIFIED_20}
			then
				notify-send "Discharging: $(batt_percentage)% left"
				NOT_NOTIFIED_20=false
				NOT_NOTIFIED_30=false
			elif [ $(batt_percentage) -le 30 ] && ${NOT_NOTIFIED_30}
			then
				notify-send -u low "Discharging: $(batt_percentage)% left"
				NOT_NOTIFIED_30=false
			fi
			;;
		Charging)
			NOT_NOTIFIED_5=true
			NOT_NOTIFIED_10=true
			NOT_NOTIFIED_20=true
			NOT_NOTIFIED_30=true
			;;
	esac
	sleep 2
done
