#!/bin/sh

SRCDIRS="./src"

if [ -n "$*" ]; then SRCDIRS="$*"; fi

echo "Creating tags for files on $SRCDIRS"
ctags -R $SRCDIR
while true; do fd --hidden -t f '.*\.[ch](pp)?' $SRCDIRS | entr ctags -a /_; done
