#!/bin/sh

SRC_DIRS="./src"
SRC_REGEX='.*\.[chi](pp|xx)?'

if [ $# -ge 1 ]; then SRC_DIRS="$1"; fi
if [ $# -eq 2 ]; then SRC_REGEX="$2"; fi

if [ ! -d "$SRC_DIRS" ]
then
	echo "Directory $SRC_DIRS not found!"
	exit
else
	while true
	do
		echo "Creating tags on $SRC_DIRS for these files:"
		fd -t f $SRC_REGEX $SRC_DIRS -x ls -1 {}

		fd -t f $SRC_REGEX $SRC_DIRS | entr -d ctags -R $SRC_DIRS
		if [ $? != 0 ]
		then
			echo "Files changed"
		else
			exit
		fi
	done
fi
