#!/bin/sh

echo "REMOVING CONTAINERS"
containers=`docker ps --all -q`
[ -n "$containers" ] && echo $containers | xargs docker rm -v

if [ "$1" = "all" ]
then
	images=`docker images -q`
	[ -n "$images" ] && echo $images | xargs docker rmi
fi

