#!/bin/sh

EXT=''
FILE_TEXT=''
FILES_TO_REMOVE=''

case $1 in
	c)
		EXT=c
		FILES_TO_REMOVE='a.out'
	;;

	cpp)
		EXT=cpp
		FILES_TO_REMOVE='a.out'
	;;

	rust)
		EXT=rs
		FILES_TO_REMOVE='main'
	;;

	*)
		echo 'Define a file type to create'
		echo -e '\tAllowed file types:'
		echo -e '\t\t- c'
		echo -e '\t\t- cpp'
		echo -e '\t\t- rust'
		exit
	;;
esac

cd /tmp
cp $HOME/.templates/temp.$EXT /tmp/main.$EXT
bash -c "nvim main.$EXT; bash"
rm -f main.$EXT $FILES_TO_REMOVE

