#!/bin/bash

PRIMARY_MON=eDP-1
SECONDARY_MON=HDMI-1

OPTIONS=("primary" "secondary")

options() {
	for (( i=$(( ${#OPTIONS[@]} - 1 )); i >= 0; i=$(( $i - 1 )) ))
	do
		echo ${OPTIONS[$i]}
	done
}

if [ $# -eq 1 ]
then
	OPTION=$1
else
	OPTION=$(options | rofi -dmenu)
fi

xrandr --auto

case $OPTION in
	primary )
		xrandr --output ${PRIMARY_MON} --pos 0x0
		xrandr --output ${SECONDARY_MON} --off
	;;
	secondary )
		xrandr --output ${SECONDARY_MON} --pos 0x0
		xrandr --output ${PRIMARY_MON} --off
	;;
esac
