#!/bin/sh

options() {
	for (( I=$((${#OPTIONS[@]} - 1)); $I >= 0; I=$(($I - 1)) ))
	do
		echo ${OPTIONS[$I]}
	done
}

OPTIONS=("double-long" "middle-top" "secondary" "double-high" "primary")
if [ $# -eq 1 ]
then
	OPTION=${OPTIONS[$(((${#OPTIONS[@]} - 1) - $1))]}
else
	OPTION=$(options | rofi -dmenu)
fi
xrandr --auto
case $OPTION in
	primary )
		xrandr --output HDMI-1 --off
		xrandr --output eDP-1 --pos 0x0
	;;
	secondary )
		xrandr --output eDP-1 --off
		xrandr --output HDMI-1 --rotate normal
		xrandr --output HDMI-1 --pos 0x0
	;;
	middle-top )
		xrandr --output HDMI-1 --above eDP-1
		xrandr --output HDMI-1 --rotate normal
		xrandr --output eDP-1 --pos $(( (1920 - 1366)/2 ))x1080
	;;
	double-high )
		xrandr --output HDMI-1 --right-of eDP-1
		xrandr --output HDMI-1 --rotate left
		xrandr --output eDP-1 --pos 0x$((1920 - 768))
	;;
	double-long )
		xrandr --output eDP-1 --right-of HDMI-1
		xrandr --output eDP-1 --pos 1920x$((1080 - 768))
	;;
esac
feh --bg-fill ~/Documents/wallpapers/current.*
