#!/bin/bash

ROOT=$(pwd)
if [ -n "$1" ]; then
	ROOT="$1"
fi

for FILE in $(fd '\.git$' -t d --hidden)
do
	cd $(realpath ${ROOT}/${FILE})/..
	OUT="$(git status -s)"
	if [ -n "${OUT}" ]
	then
		echo -e "$(pwd): \e[1;91mGit repo not up-to-date\e[m"
	else
		echo -e "$(pwd): \e[1;92mGit repo up-to-date\e[m"
	fi
done
