#!/bin/sh

SKPID=`ps -e | grep screenkey | awk '{print $1}'`
if [ -z "$SKPID" ]
then
	screenkey\
		--no-systray\
		--opacity 0\
		--timeout 0.7\
		-p fixed\
		-g '40%x5%-30%-10%' &
else
	kill $SKPID
fi

